name: Run 3CX Scraper

on:
  schedule:
    - cron: '*/30 * * * *'
  workflow_dispatch:

jobs:
  run-scraper:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            xvfb \
            chromium-browser \
            chromium-chromedriver \
            fonts-liberation \
            libasound2 \
            libatk-bridge2.0-0 \
            libatk1.0-0 \
            libatspi2.0-0 \
            libdrm2 \
            libgtk-3-0 \
            libnspr4 \
            libnss3 \
            libxcomposite1 \
            libxdamage1 \
            libxfixes3 \
            libxrandr2 \
            libxss1 \
            libxtst6
          
          # Verify installations
          echo "Checking installed versions..."
          chromium-browser --version
          chromedriver --version
          xvfb-run --help > /dev/null && echo "Xvfb OK" || echo "Xvfb FAILED"

      - name: Cache Python dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Create requirements.txt if missing
        run: |
          if [ ! -f requirements.txt ]; then
            echo "Creating requirements.txt..."
            cat > requirements.txt << EOF
          selenium==4.15.0
          odoorpc==0.10.0
          EOF
          fi

      - name: Verify environment variables
        run: |
          echo "Checking environment variables..."
          if [ -z "$THREECX_URL" ]; then echo "ERROR: THREECX_URL not set"; exit 1; fi
          if [ -z "$THREECX_USER" ]; then echo "ERROR: THREECX_USER not set"; exit 1; fi
          if [ -z "$THREECX_PASS" ]; then echo "ERROR: THREECX_PASS not set"; exit 1; fi
          if [ -z "$ODOO_URL" ]; then echo "ERROR: ODOO_URL not set"; exit 1; fi
          if [ -z "$ODOO_DB" ]; then echo "ERROR: ODOO_DB not set"; exit 1; fi
          if [ -z "$ODOO_USER" ]; then echo "ERROR: ODOO_USER not set"; exit 1; fi
          if [ -z "$ODOO_PASS" ]; then echo "ERROR: ODOO_PASS not set"; exit 1; fi
          echo "All environment variables are set"
        env:
          THREECX_URL: ${{ secrets.THREECX_URL }}
          THREECX_USER: ${{ secrets.THREECX_USER }}
          THREECX_PASS: ${{ secrets.THREECX_PASS }}
          ODOO_URL: ${{ secrets.ODOO_URL }}
          ODOO_DB: ${{ secrets.ODOO_DB }}
          ODOO_USER: ${{ secrets.ODOO_USER }}
          ODOO_PASS: ${{ secrets.ODOO_PASS }}

      - name: Test Chrome and display
        run: |
          export DISPLAY=:99
          Xvfb :99 -screen 0 1920x1080x24 &
          sleep 3
          chromium-browser --headless --disable-gpu --dump-dom https://www.google.com > /dev/null 2>&1 && echo "Chrome test OK" || echo "Chrome test FAILED"

      - name: Run scraper with enhanced logging
        env:
          CHROME_BIN: /usr/bin/chromium-browser
          CHROMEDRIVER_PATH: /usr/bin/chromedriver
          ODOO_URL: ${{ secrets.ODOO_URL }}
          ODOO_DB: ${{ secrets.ODOO_DB }}
          ODOO_USER: ${{ secrets.ODOO_USER }}
          ODOO_PASS: ${{ secrets.ODOO_PASS }}
          THREECX_URL: ${{ secrets.THREECX_URL }}
          THREECX_USER: ${{ secrets.THREECX_USER }}
          THREECX_PASS: ${{ secrets.THREECX_PASS }}
          DISPLAY: :99
          PYTHONUNBUFFERED: 1
        run: |
          echo "Starting Xvfb..."
          Xvfb :99 -screen 0 1920x1080x24 &
          sleep 3
          
          echo "Running scraper..."
          python3 scrapper.py
          
          echo "Scraper completed with exit code: $?"

      - name: Upload logs on failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: scraper-logs
          path: |
            *.log
            /tmp/*.log
          retention-days: 1