name: Run 3CX Scraper

on:
  schedule:
    - cron: '*/30 * * * *'
  workflow_dispatch:

jobs:
  run-scraper:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install system dependencies (Xvfb, Chromium, Chromedriver)
        run: |
          sudo apt-get update
          sudo apt-get install -y xvfb chromium-driver fonts-liberation libappindicator3-1 libasound2 libatk-bridge2.0-0 libatk1.0-0 libcups2 libdbus-1-3 libgdk-pixbuf2.0-0 libnspr4 libnss3 libxcomposite1 libxdamage1 libxrandr2 xdg-utils wget
          wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
          sudo apt install -y ./google-chrome-stable_current_amd64.deb
          google-chrome --version
          chromedriver --version

      - name: Install Python dependencies
        run: pip install -r requirements.txt

      - name: Run scraper with Xvfb
        env:
          DISPLAY: ":99"
          CHROME_BIN: "/usr/bin/google-chrome"
          CHROMEDRIVER_PATH: "/usr/bin/chromedriver"
          ODOO_URL: ${{ secrets.ODOO_URL }}
          ODOO_DB: ${{ secrets.ODOO_DB }}
          ODOO_USER: ${{ secrets.ODOO_USER }}
          ODOO_PASS: ${{ secrets.ODOO_PASS }}
          THREECX_URL: ${{ secrets.THREECX_URL }}
          THREECX_USER: ${{ secrets.THREECX_USER }}
          THREECX_PASS: ${{ secrets.THREECX_PASS }}
        run: |
          Xvfb :99 -screen 0 1920x1080x24 &  # start virtual display
          sleep 3                            # wait for Xvfb to fully launch
          python3 scrapper.py               # run the actual scraper script
